graph TD
   Producer1-. Queue:\\TEST.FOO, 60 messages .->Broker1
   Broker1-->Broker2
   Broker1-. Queue:\\TEST.FOO, 20 messages .->Consumer1
   Broker2-. Queue:\\TEST.FOO, 20 messages .->Consumer2
   Broker2-. Queue:\\TEST.FOO, 20 messages .->Consumer3
   