graph TD
   Sender1-. Queue:\\TEST.FOO, 60 messages .->NoB1
   NoB1-->NoB2
   NoB1-. Queue:\\TEST.FOO, 20 messages .->Receiver1
   NoB2-. Queue:\\TEST.FOO, 20 messages .->Receiver2
   NoB2-. Queue:\\TEST.FOO, 20 messages .->Receiver3